# Generated by Django 4.1.4 on 2022-12-14 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompletedTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time_created", models.DateTimeField(auto_now_add=True)),
                ("type", models.CharField(max_length=255)),
                ("amount", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="LiquidDataPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.FloatField()),
                ("description", models.TextField()),
                (
                    "validity",
                    models.CharField(
                        choices=[
                            ("Daily", "Daily"),
                            ("7 Days", "7 Days"),
                            ("30 Days", "30 Days"),
                            ("Non Expiry", "Non Expiry"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SavedTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(default="N/A", max_length=255)),
                ("last_name", models.CharField(default="N/A", max_length=255)),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("amount", models.FloatField()),
                ("reference_number", models.CharField(max_length=255)),
                ("request_reference", models.CharField(max_length=255)),
                ("product_id", models.IntegerField()),
                ("session_uuid", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                ("date_time_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ServiceCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("website", models.URLField()),
                ("image", models.ImageField(upload_to="CompanyImages")),
                ("dpo_company_token", models.CharField(max_length=255)),
                ("active_status", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=255)),
                ("balance", models.FloatField(default=0.0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
