# Generated by Django 4.1.4 on 2022-12-14 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LiquidBundle", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servicecompany", options={"verbose_name_plural": "Service Companies"},
        ),
    ]
