# Generated by Django 4.1.4 on 2022-12-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LiquidBundle", "0002_alter_servicecompany_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="liquiddatapackage",
            name="identifier",
            field=models.IntegerField(default=0),
        ),
    ]
