# Generated by Django 4.1.4 on 2022-12-15 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("LiquidBundle", "0003_liquiddatapackage_identifier"),
    ]

    operations = [
        migrations.RemoveField(model_name="completedtransaction", name="amount",),
        migrations.AddField(
            model_name="completedtransaction",
            name="lte_number",
            field=models.CharField(default="260630999999", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="completedtransaction",
            name="package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="LiquidBundle.liquiddatapackage",
            ),
        ),
        migrations.AddField(
            model_name="completedtransaction",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
