# Generated by Django 4.1.4 on 2022-12-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LiquidBundle", "0007_completedtransaction_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="KazangSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_uuid", models.CharField(max_length=255)),
                ("date_time_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
